In [1]:
import getpass
import pandas as pd
import psycopg2 
import json
import requests
from datetime import datetime
import numpy as np

# Variables
weekly_payout = 23.21

# Define PostgreSQL database connection parameters
# user = input("username")

api_key = getpass.getpass("Enter DataGolf API key:")
host = getpass.getpass("Enter Database Host:")
port = "5432" # The default port for PosgreSQL Server
dbname = 'postgres'
user = getpass.getpass("Enter Username:")
password = getpass.getpass("Enter Password:")

# Define a SQLAlchemy URI string for connecting to the database
# The URI structure is [DB_FLAVOR]+[DB_PYTHON_LIBRARY]://[USERNAME]:[PASSWORD]@[DB_HOST]:[PORT]/[DB_NAME]
db_URI = f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{dbname}"

In [ ]:
# A helper function to open a psycopg2 connection, set auto-commit to true, execute the sql, and close the connection.
# This will mainly be used for writing to the db
# def execute_sql(sql, echo=False):
#     try:
#         pg_conn = psycopg2.connect(
#             dbname=dbname,
#             user=user,
#             password=password,
#             host=host,
#             port=port
#         )
#     except psycopg2.Error as e:
#         error_message = e.pgerror
#         print("Error Connecting:", error_message)
   
#     try:
#         # Set the connection to autocommit (everything is treated as an individual transaction)
#         pg_conn.set_session(autocommit=True)
        
#         # The cursor is used to execute ddl statements.
#         pg_cursor = pg_conn.cursor() 

#         pg_cursor.execute(sql)
#         if echo:
#             print(sql)

#         results = pg_cursor.fetchall()
#         return results
    
#     except psycopg2.Error as e:
#         error_message = e.pgerror
#         print("SQL Failed:", error_message)
#         return []
    
#     finally:
#         if pg_cursor:
#             pg_cursor.close()
#         if pg_conn:
#             pg_conn.close()

In [2]:
#function for uploading df to aws postgre SQL database
def insert_df_to_sql(table_name, df):
    try:
        pg_conn = psycopg2.connect(
            dbname=dbname,
            user=user,
            password=password,
            host=host,
            port=port
        )
    except psycopg2.Error as e:
        error_message = e.pgerror
        print("Error Connecting:", error_message)

    try:
        # Create a cursor object
        cursor = pg_conn.cursor()

        # Convert the DataFrame to a list of tuples for insertion
        insert_query = f"INSERT INTO {table_name} ({', '.join(df.columns)}) VALUES ({', '.join(['%s'] * len(df.columns))})"
        data_to_insert = df.to_records(index=False).tolist()

        # Insert data using executemany()
        cursor.executemany(insert_query, data_to_insert)

        # Commit the transaction
        pg_conn.commit()
        print("Data inserted successfully!")
    except psycopg2.Error as e:
        error_message = e.pgerror
        print("Exception uploading to "+table_name+" table."+error_message)

    finally:
        # Close the cursor and connection
        cursor.close()
        pg_conn.close()

In [ ]:
# def psyco_read_sql(sql):
#     try:
#         pg_conn = psycopg2.connect(
#             dbname=dbname,
#             user=user,
#             password=password,
#             host=host,
#             port=port
#         )
#     except psycopg2.Error as e:
#         error_message = e.pgerror
#         print("Error Connecting:", error_message)

#     # Use pd.read_sql to execute the query and load data into a DataFrame
#     df = pd.read_sql(sql, pg_conn)

#     # Print the DataFrame
#     print(df)

#     # Close the database connection
#     pg_conn.close()

In [3]:
#function to gather df from json response
def df_from_json(feed):
    response = requests.get(feed)
    json_data = response.json()
    df = pd.DataFrame(json_data)
    return df

# Check for missing players

In [16]:
#get the players list from datagolf
players_dg = df_from_json('https://feeds.datagolf.com/get-player-list?file_format=json&key='+api_key)

#get the unique dg_id from players already in aws db
players_aws = pd.read_sql(sql = """
                          select distinct dg_id from player;
                          """, con=db_URI)

In [17]:
#find players that are in the datagolf db that are missing from the aws db
missing_players = players_dg[~players_dg['dg_id'].isin(players_aws['dg_id'])] # ~ operator inverts - this is looking for all golfers in datagolf db that are not in aws
missing_players

      amateur        country country_code     dg_id          player_name
485         1  United States          USA     34995  Chirravuri, Mahanth
535         1  United States          USA     34994    Coleman, Hamilton
1044        1  United States          USA     35003       Gimenez, Lucas
1251        1  United States          USA  30040693  Herrington, Jackson
1315        1  United States          USA  30044977       Holtz, Brandon
1720        0  United States          USA     33957          Kumar, Noah
2502        1  United States          USA     35012          Price, Alex
2514        1      Argentina          ARG  30035862       Pulcini, Mateo
3373        1          India          IND     31841        Yadav, Deepak

In [6]:
#if there's missing players, add them to the aws db
if(len(missing_players['player_name'])>0):
    insert_df_to_sql('player', missing_players)

Data inserted successfully!

# Check for Event Updates

In [14]:
#dynamic current year so script can be re-used next year
current_year = datetime.now().year

#capture datagolf events and the current year events already uploaded to aws
events_dg = df_from_json('https://feeds.datagolf.com/historical-raw-data/event-list?file_format=json&key='+api_key)
events_aws_current_year = pd.read_sql(sql = f"""
                          select event_id from event where calendar_year = {current_year};
                          """, con=db_URI)

#filter datagolf historical events to current year, pga
events_dg_current_year = events_dg[(events_dg['tour'] == 'pga') & (events_dg['calendar_year'] == events_dg['calendar_year'].max())]

In [15]:
#find which events are not in aws
missing_events = events_dg_current_year[~events_dg_current_year['event_id'].isin(events_aws_current_year['event_id'])]
missing_events

,calendar_year,date,event_id,event_name,sg_categories,tour,traditional_stats
0,2026,2026-04-05,41,Valero Texas Open,yes,pga,yes
6,2026,2026-03-29,20,Texas Children's Houston Open,yes,pga,yes

# Check for DFS event

In [8]:
#create array to hold missing dfs event ids
no_dfs = []

#loop through each missing event to check for empty response code 400
for id_ev in missing_events['event_id']:
    feed = 'https://feeds.datagolf.com/historical-dfs-data/points?tour=pga&site=fanduel&event_id='+str(id_ev)+'&year='+str(current_year)+'&file_format=json&key='+api_key
    response = requests.get(feed)
    if(response.status_code == 400):
        no_dfs.append(id_ev)

#remove any missing events from missing_events df as the DFS event may not be ready yet (or will never exist)
missing_events = missing_events[~missing_events['event_id'].isin(no_dfs)]
missing_events

,calendar_year,date,event_id,event_name,sg_categories,tour,traditional_stats
0,2026,2026-03-29,20,Texas Children's Houston Open,yes,pga,yes

In [10]:
#if there's any missing events, add them to the aws db
if(len(missing_events['event_id'])>0):
    missing_events_w_dfs_payout = missing_events.copy().drop(['sg_categories', 'tour', 'traditional_stats'], axis=1)
    missing_events_w_dfs_payout['dfs_payout'] = None
    insert_df_to_sql('event', missing_events_w_dfs_payout)

Data inserted successfully!

In [11]:
pd.read_sql(f"""select * from event where calendar_year = {current_year} order by date desc""", con=db_URI)

,id_event,calendar_year,event_id,date,event_name,dfs_payout
0,99fa63fa-73ee-489d-930b-ef9ef1317f19,2026,475,2026-03-22,Valspar Championship,None
1,a09643c4-385c-41c8-bc8c-3ff7acc895c2,2026,11,2026-03-15,THE PLAYERS Championship,None
2,c231e8e7-65de-4f2a-b7a8-6fe5cb296467,2026,483,2026-03-08,Puerto Rico Open,None
3,c910f6c2-2e6e-4c8d-be2b-4684f85f401a,2026,9,2026-03-08,Arnold Palmer Invitational presented by Master...,None
4,00b62349-9495-4e99-98d2-c2464aea407b,2026,10,2026-03-01,Cognizant Classic in The Palm Beaches,None
5,f8fdc2cb-50d9-41d2-b0cc-6d6069e98199,2026,7,2026-02-22,The Genesis Invitational,None
6,135afec5-f913-4ac7-9bb4-d77db5875188,2026,5,2026-02-15,AT&T Pebble Beach Pro-Am,None
7,fa33044d-3d9c-4a69-8c1a-8695fb82c0c5,2026,3,2026-02-08,WM Phoenix Open,None
8,f44aff21-82f0-4f05-ad9e-3dca367936b2,2026,4,2026-02-01,Farmers Insurance Open,None
9,9a947dc2-923d-4658-8876-e8ece346f707,2026,2,2026-01-25,The American Express,None
10,f149824d-8742-4a7f-8d57-11bea3e768a0,2026,6,2026-01-18,Sony Open in Hawaii,None

# Parse Raw Player Scoring & Data

In [12]:
#get headers from an event with everthing documented (event 2 in 2025 is one example)
event_for_names = df_from_json('https://feeds.datagolf.com/historical-raw-data/rounds?tour=pga&event_id=2&year=2025&file_format=json&key='+api_key)
basic_names = ['event_id', 'calendar_year', 'dg_id', 'round', 'fin_text']
stat_names = basic_names + pd.json_normalize(event_for_names['scores'].loc[0]['round_1'], max_level=0).columns.tolist()
stat_names.sort()

#create placeholder array to store round information.  *Getting warnings appending to pre-set dataframe so went the array route for now.  Could potentially pre-define/pre-fill df with None but this gets tricky because some rounds will not be uploaded due to CUT or WD
rounds = []

for id_ev in missing_events['event_id']:
    #get the event historical data
    event_temp = df_from_json('https://feeds.datagolf.com/historical-raw-data/rounds?tour=pga&event_id='+str(id_ev)+'&year='+str(current_year)+'&file_format=json&key='+api_key)
    
    #loop through players
    player_summary = pd.json_normalize(event_temp['scores'], max_level=0)
    for row in player_summary.iterrows():
        player = row[1]

        #create array of round info.  If there is a missing round, do not add
        event_rounds = []
        if pd.notna(player['round_1']):
            event_rounds = event_rounds + [pd.json_normalize(player['round_1'], max_level = 0)]
        if pd.notna(player['round_2']):
            event_rounds = event_rounds + [pd.json_normalize(player['round_2'], max_level = 0)]
        if pd.notna(player['round_3']):
            event_rounds = event_rounds + [pd.json_normalize(player['round_3'], max_level = 0)]
        if pd.notna(player['round_4']):
            event_rounds = event_rounds + [pd.json_normalize(player['round_4'], max_level = 0)]

        for index, rnd in enumerate(event_rounds):
            #add player summary info (basic_names) to each round df and add to rounds
            basic_cols = pd.DataFrame({'dg_id':[player['dg_id']], 'fin_text':[player['fin_text']], 'round':[index+1], 'event_id':[id_ev], 'calendar_year':[current_year]})
            rnd[basic_cols.columns] = basic_cols

            #find differences in the column headers (if any - some events do not contain all the data, so will need to fill with NA)
            diffs = set(stat_names)-set(rnd.columns)

            #add NA to missing columns
            for item in diffs:
                rnd[item] = None

            #sort the columns so array can be easily converted to df later
            rnd_sorted = rnd.copy()[sorted(rnd.columns)]

            #append array
            rounds.append(rnd_sorted.loc[0].values)

#convert to dataframe and normalize NAs
rounds = pd.DataFrame(rounds, columns=stat_names).replace([np.nan, 'missing'], None, inplace=False)
rounds.sample(10)

,birdies,bogies,calendar_year,course_name,course_num,course_par,dg_id,doubles_or_worse,driving_acc,driving_dist,...,score,scrambling,sg_app,sg_arg,sg_ott,sg_putt,sg_t2g,sg_total,start_hole,teetime
2759,0,4,2026,TPC Scottsdale (Stadium Course),510,71,31585,3,0.429,287.9,...,82,0.25,-2.251,-5.533,-0.758,-2.572,-8.542,-11.114,10,8:59am
1999,2,5,2026,The Riviera Country Club,500,71,20722,0,0.786,289.6,...,74,0.667,-2.956,0.005,0.635,-1.821,-2.316,-4.137,1,7:45am
2438,6,0,2026,TPC Scottsdale (Stadium Course),510,71,17606,0,0.714,314.1,...,65,0.667,4.701,-0.045,0.698,-0.668,5.354,4.685,1,8:45am
2756,2,7,2026,TPC Scottsdale (Stadium Course),510,71,21756,1,0.357,308.2,...,79,0.364,-1.068,-1.033,-3.183,-3.43,-5.284,-8.713,10,1:28pm
80,2,5,2026,Innisbrook Resort and Golf Club - Copperhead C...,665,71,25003,0,0.385,286.0,...,74,0.5,0.008,-0.041,-1.743,-0.462,-1.776,-2.237,1,1:36pm
2356,4,4,2026,Spyglass Hill Golf Course,205,72,19477,0,0.5,289.9,...,72,0.5,-0.421,-0.133,-0.163,-1.757,-0.717,-2.475,1,9:37am
2665,3,3,2026,TPC Scottsdale (Stadium Course),510,71,14509,0,1.0,307.1,...,71,0.875,-1.494,1.289,2.275,-2.184,2.07,-0.114,1,12:22pm
2148,8,0,2026,Pebble Beach Golf Links,5,72,11889,0,0.714,290.6,...,64,1.0,-1.101,3.105,1.554,1.542,3.558,5.1,1,10:29am
2582,7,4,2026,TPC Scottsdale (Stadium Course),510,71,16162,0,0.5,302.6,...,68,0.7,-0.626,1.66,-1.145,1.797,-0.111,1.685,10,10:24am
974,5,3,2026,Grand Reserve Golf Club,940,72,19960,0,0.571,298.5,...,70,None,None,None,None,None,None,0.206,1,8:40am

## Upload Any Missing Courses

In [9]:
new_courses = rounds.drop_duplicates('course_num')[['course_name', 'course_num', 'course_par']].reset_index().drop('index', axis=1)
courses_aws = pd.read_sql(sql="""SELECT * FROM COURSE;""", con=db_URI)
missing_courses = new_courses[~new_courses['course_num'].isin(courses_aws['course_num'])]
missing_courses

NameError: name 'rounds' is not defined

In [14]:
#if there's missing courses, add them to the aws db
if(len(missing_courses['course_num'])>0):
    insert_df_to_sql('course', missing_courses)

## Upload Player Scoring

In [14]:
#cleanup rounds df
rounds_clean = rounds.drop(['course_name', 'course_par', 'fin_text'], axis=1)

#get necessary event information
events_aws = pd.read_sql(sql=f"""SELECT id_event, event_id, calendar_year FROM EVENT WHERE CALENDAR_YEAR = {current_year};""", con=db_URI)
events_aws['id_event'] = events_aws['id_event'].astype(str)
events_aws

#get necessary course information
courses_aws = pd.read_sql(sql="""SELECT id_course, course_num FROM COURSE;""", con=db_URI)

#replace aws id's with dg
rounds_clean = pd.merge(rounds_clean, events_aws, on=['event_id', 'calendar_year'], how='left').drop(['event_id', 'calendar_year'], axis=1)
rounds_clean = pd.merge(rounds_clean, courses_aws, on=['course_num'], how='left').drop('course_num', axis=1)

#preview
rounds_clean.sample(10)

,birdies,bogies,dg_id,doubles_or_worse,driving_acc,driving_dist,eagles_or_better,gir,great_shots,pars,...,sg_app,sg_arg,sg_ott,sg_putt,sg_t2g,sg_total,start_hole,teetime,id_event,id_course
317,2,6,16341,0,0.769,262.7,0,0.389,3.0,10,...,-1.495,-0.275,0.46,-1.995,-1.31,-3.306,1,9:14am,99fa63fa-73ee-489d-930b-ef9ef1317f19,c5820d32-533e-49b2-b2c5-0d222101e4b3
1856,3,0,14636,0,0.286,294.5,1,0.611,3.0,14,...,0.905,-0.168,-1.417,3.112,-0.68,2.431,1,9:45am,f8fdc2cb-50d9-41d2-b0cc-6d6069e98199,005ab16a-8619-4b83-b824-47808cc6688d
744,3,2,12577,1,0.5,296.8,0,0.722,2.0,12,...,0.699,-0.45,1.134,-1.998,1.383,-0.615,10,1:06pm,a09643c4-385c-41c8-bc8c-3ff7acc895c2,6e2d922c-1691-4e8d-bc60-f319d0ac7faf
1530,4,1,15470,0,0.571,280.5,0,0.833,3.0,13,...,-0.027,0.878,0.62,1.829,1.471,3.301,10,6:45am,00b62349-9495-4e99-98d2-c2464aea407b,d5d1db75-9c80-4dd6-b1d7-9143e8e4ed15
1670,4,0,11276,1,0.357,279.0,0,0.778,5.0,13,...,2.298,-1.263,-0.182,1.447,0.853,2.301,10,7:21am,00b62349-9495-4e99-98d2-c2464aea407b,d5d1db75-9c80-4dd6-b1d7-9143e8e4ed15
262,3,4,16715,0,0.615,276.9,0,0.722,2.0,11,...,1.374,-1.27,0.38,-1.429,0.484,-0.946,1,10:45am,99fa63fa-73ee-489d-930b-ef9ef1317f19,c5820d32-533e-49b2-b2c5-0d222101e4b3
107,5,4,25002,0,0.538,275.2,0,0.556,2.0,9,...,-1.346,0.888,-0.529,1.689,-0.987,0.703,1,11:20am,99fa63fa-73ee-489d-930b-ef9ef1317f19,c5820d32-533e-49b2-b2c5-0d222101e4b3
1534,5,1,18424,0,0.643,283.5,0,0.778,2.0,12,...,0.024,-0.296,1.12,3.452,0.848,4.301,1,11:59am,00b62349-9495-4e99-98d2-c2464aea407b,d5d1db75-9c80-4dd6-b1d7-9143e8e4ed15
1046,2,2,16757,0,0.5,293.5,0,0.556,None,14,...,None,None,None,None,None,-1.794,1,8:30am,c231e8e7-65de-4f2a-b7a8-6fe5cb296467,de80fb0b-5bc8-46a9-8155-fd49e3e78d7d
769,1,6,14509,0,0.5,271.9,0,0.389,2.0,11,...,0.38,-1.182,-0.15,-2.916,-0.952,-3.869,1,1:24pm,a09643c4-385c-41c8-bc8c-3ff7acc895c2,6e2d922c-1691-4e8d-bc60-f319d0ac7faf

In [15]:
insert_df_to_sql('round', rounds_clean)

Data inserted successfully!

# Upload Player DFS

In [16]:
#get all stat headers for dfs scoring (they all exist for event 2 in 2025)
dfs = df_from_json('https://feeds.datagolf.com/historical-dfs-data/points?tour=pga&site=fanduel&event_id=2&year=2025&file_format=json&key='+api_key)
stat_names = pd.json_normalize(dfs['dfs_points'].loc[0], max_level=0).drop(['ownership', 'player_name'], axis=1).columns.tolist()+['id_event']
stat_names.sort()

#set placeholder array
dfs_array = []

#loop through the missing events
for id_ev in missing_events['event_id']:

    #get the event historical data
    event_temp = df_from_json('https://feeds.datagolf.com/historical-dfs-data/points?tour=pga&site=fanduel&event_id='+str(id_ev)+'&year='+str(current_year)+'&file_format=json&key='+api_key)

    #loop through golfer's dfs event summary
    for player in event_temp['dfs_points']:
        #get the dfs points, add calendar year and event id so it can be merged with the aws id_event
        dfs_pts = pd.json_normalize(player, max_level=0).drop(['player_name', 'ownership'], axis=1)
        dfs_pts['calendar_year'] = current_year
        dfs_pts['event_id'] = id_ev
        dfs_pts = pd.merge(dfs_pts, events_aws, on=['event_id', 'calendar_year']).drop(['calendar_year', 'event_id'], axis=1)
        
        #find differences in the column headers (if any - some events do not contain all the data, so will need to fill with NA)
        diffs = set(stat_names)-set(dfs_pts.columns)

        #add NA to missing columns
        for item in diffs:
            dfs_pts[item] = None
    
        #sort the columns so array can be easily converted to df later
        dfs_pts_sorted = dfs_pts.copy()[sorted(dfs_pts.columns)]

        #append to placeholder array
        dfs_array.append(dfs_pts_sorted.loc[0].values)

#convert to dataframe and normalize NAs
dfs_array = pd.DataFrame(dfs_array, columns=stat_names).replace([np.nan, 'missing'], None, inplace=False)
dfs_array.sample(10)

,bogey_free_pts,bounce_back_pts,dg_id,fin_text,finish_pts,five_birdie_pts,hole_score_pts,id_event,salary,streak_pts,total_pts
783,0,0.9,25319,T60,0,4,56.1,fa33044d-3d9c-4a69-8c1a-8695fb82c0c5,7000.0,1.2,62.2
319,0,0.3,21943,T61,0,0,57.2,c231e8e7-65de-4f2a-b7a8-6fe5cb296467,None,0.6,58.1
769,0,1.2,21688,T54,0,8,57.6,fa33044d-3d9c-4a69-8c1a-8695fb82c0c5,8000.0,1.8,68.6
818,0,0.0,21889,CUT,0,0,21.8,fa33044d-3d9c-4a69-8c1a-8695fb82c0c5,7000.0,0.0,21.8
275,0,0.9,23048,T26,2,12,70.1,c231e8e7-65de-4f2a-b7a8-6fe5cb296467,None,3.6,88.6
129,0,0.6,17786,CUT,0,0,6.4,99fa63fa-73ee-489d-930b-ef9ef1317f19,7000.0,0.0,7.0
841,0,0.6,21756,CUT,0,0,11.0,fa33044d-3d9c-4a69-8c1a-8695fb82c0c5,8300.0,0.0,11.6
160,0,1.2,13562,T27,2,8,59.8,a09643c4-385c-41c8-bc8c-3ff7acc895c2,11200.0,4.2,75.2
489,0,0.9,10104,T52,0,8,59.1,00b62349-9495-4e99-98d2-c2464aea407b,9400.0,0.6,68.6
704,0,0.3,25569,T55,0,4,64.1,135afec5-f913-4ac7-9bb4-d77db5875188,7800.0,1.8,70.2

In [17]:
insert_df_to_sql('dfs_total', dfs_array)

Data inserted successfully!